# Generated by Django 4.1.9 on 2023-06-26 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('widthdrawal', 'Widthdrawal'), ('deposit', 'Deposit'), ('transfer', 'Transfer')], default='widthdrawal', max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('declined', 'Declined')], max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
